import fs from 'node:fs';
import http from 'node:http';
import path from 'node:path';
import puppeteer from 'puppeteer-core';

// Generate from the reviewed viewer, so fixes are not lost in a second scene copy.
const viewer=fs.readFileSync('chain-reaction-viewer.html','utf8');
let scene=viewer.split('<script type="module">')[1].split('let time=0, playing=true, speed=1;')[0];
scene=scene.replace(/^import .*OrbitControls.*\r?\n/m,'').replace(/^import .*GLTFExporter.*\r?\n/m,'')
  .replace(/^document.querySelector\('\[data-t=.*\r?\n/gm,'')
  .replace(/^  const stages=.*\r?\n/m,'').replace(/^  document.querySelector\('#stage'\).*\r?\n/m,'')
  .replace('renderer.setPixelRatio(Math.min(devicePixelRatio,2));','renderer.setPixelRatio(1);renderer.setSize(1920,1080,false);')
  .replace('new T.WebGLRenderer({canvas,antialias:true})','new T.WebGLRenderer({canvas,antialias:true,preserveDrawingBuffer:true})')
  .replace('45,innerWidth/innerHeight','45,1920/1080')
  .replace(/const controls=new OrbitControls[\s\S]*?controls.maxDistance=60; controls.minDistance=1.2;/,'');
const cues=viewer.slice(viewer.indexOf("audioClip('roll.mp3'"),viewer.indexOf('function syncAudio()'));
const tones=viewer.match(/const soundEvents=([^;]+);/)[1];
scene+=`\nconst audioCues=[];function audioClip(file,start,duration,volume,options={}){audioCues.push({file,start,duration,volume,...options});}\n${cues}\nconst toneCues=${tones};\n`;
scene+=fs.readFileSync('composition-camera.js','utf8');
scene+='\nwindow.__chainReview={renderAt,SIM,E,DURATION,audioCues,toneCues,scene,camera,spiralBall,blueBall,gongHanger,flag,finaleTiles};\n';
fs.writeFileSync('scene.js','// Generated by build.mjs from chain-reaction-viewer.html and composition-camera.js.\n'+scene);
const template=fs.readFileSync('index.template.txt','utf8');
const html=audio=>template.replace('<!-- AUDIO -->',audio).replace('<script type="module" src="scene.js"></script>',`<script type="module">${scene}</script>`);
fs.writeFileSync('index.html',html(''));
const root=process.cwd(),server=http.createServer((req,res)=>{
  const file=path.join(root,decodeURIComponent(req.url.split('?')[0]));
  if(!file.startsWith(root)||!fs.existsSync(file)){res.writeHead(404);res.end();return;}
  res.setHeader('Content-Type',file.endsWith('.html')?'text/html':'text/javascript');res.end(fs.readFileSync(file));
});
await new Promise(r=>server.listen(0,'127.0.0.1',r));
let browser,manifest;
try{
  browser=await puppeteer.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true,args:['--no-sandbox']});
  const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(`http://127.0.0.1:${server.address().port}/index.html`);
  await page.waitForFunction(()=>window.__chainReview);
  manifest=await page.evaluate(()=>{const v=window.__chainReview;return {duration:v.DURATION,events:v.E,audio:v.audioCues,tones:v.toneCues};});
  if(errors.length)throw new Error(errors.join('\n'));
}finally{await browser?.close();server.close();}
// Bake the viewer's procedural chimes to WAV for framework-owned audio.
for(const [i,[start,frequency,duration,volume]] of manifest.tones.entries()){
  const rate=44100,count=Math.ceil(rate*duration),wav=Buffer.alloc(44+count*2);
  wav.write('RIFF');wav.writeUInt32LE(wav.length-8,4);wav.write('WAVEfmt ',8);wav.writeUInt32LE(16,16);wav.writeUInt16LE(1,20);wav.writeUInt16LE(1,22);wav.writeUInt32LE(rate,24);wav.writeUInt32LE(rate*2,28);wav.writeUInt16LE(2,32);wav.writeUInt16LE(16,34);wav.write('data',36);wav.writeUInt32LE(count*2,40);
  for(let n=0;n<count;n++){const t=n/rate;let sample=0;for(const [ratio,gain] of [[1,1],[2.76,.35],[5.4,.12]])sample+=volume*gain*Math.exp(Math.log(.0001/(volume*gain))*t/duration)*Math.sin(2*Math.PI*frequency*ratio*t);wav.writeInt16LE(Math.round(Math.max(-1,Math.min(1,sample))*32767),44+n*2);}
  const file=`chain-tone-${i}.wav`;fs.writeFileSync('assets/audio/'+file,wav);manifest.audio.push({file,start,duration,volume:1});
}
const clips=[];
for(const cue of manifest.audio){
  if(!cue.loop){clips.push(cue);continue;}
  for(let elapsed=0;elapsed<cue.duration;elapsed+=3.48)clips.push({...cue,start:cue.start+elapsed,duration:Math.min(3.48,cue.duration-elapsed),fadeIn:elapsed===0?cue.fadeIn:0,fadeOut:elapsed+3.48>=cue.duration?cue.fadeOut:0});
}
const audio=clips.map((c,i)=>{
  const points=[[0,c.fadeIn?0:c.volume]];if(c.fadeIn)points.push([c.fadeIn,c.volume]);if(c.fadeOut)points.push([Math.max(c.fadeIn||0,c.duration-c.fadeOut),c.volume],[c.duration,0]);
  const automation=JSON.stringify({version:1,lanes:[{target:'volume',points:points.map(([t,v])=>({t,v}))}]}).replaceAll('"','&quot;');
  return `<audio id="cue-${i}" src="assets/audio/${c.file}" data-start="${c.start}" data-duration="${c.duration}" data-media-start="${c.offset||0}" data-track-index="${c.file==='roll.mp3'?1:c.file==='click.mp3'?2+i%2:4}" data-automation="${automation}"></audio>`;
}).join('\n');
fs.writeFileSync('index.html',html(audio));fs.writeFileSync('assets/full-scene-timing.json',JSON.stringify(manifest,null,2));
console.log(`Built full scene: ${manifest.duration}s, 1920x1080, ${clips.length} sound clips. No MP4 exported.`);
